# Generated by Django 5.2.3 on 2025-08-20 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 8, 20, 21, 40, 56, 388533, tzinfo=datetime.timezone.utc)),
        ),
    ]
