# Generated by Django 5.2.3 on 2025-08-20 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 8, 20, 21, 52, 37, 666357, tzinfo=datetime.timezone.utc)),
        ),
    ]
