# Generated by Django 5.2.3 on 2025-08-22 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_new_alter_article_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 8, 22, 10, 48, 27, 603483, tzinfo=datetime.timezone.utc)),
        ),
    ]
