# Generated by Django 5.2.3 on 2025-08-31 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_status_alter_article_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 8, 31, 15, 38, 46, 864758, tzinfo=datetime.timezone.utc)),
        ),
    ]
