# Generated by Django 5.2.3 on 2025-09-02 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_slug_alter_article_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 9, 2, 12, 22, 45, 88048, tzinfo=datetime.timezone.utc)),
        ),
    ]
