# Generated by Django 5.1.5 on 2025-09-17 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_up_date_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 9, 17, 11, 32, 38, 258811, tzinfo=datetime.timezone.utc)),
        ),
    ]
