# Generated by Django 5.2.3 on 2025-09-21 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_article_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 9, 21, 8, 31, 52, 226745, tzinfo=datetime.timezone.utc)),
        ),
    ]
