# Generated by Django 5.2.3 on 2025-09-21 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=750, unique_for_date='up_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 9, 21, 16, 46, 20, 678297, tzinfo=datetime.timezone.utc)),
        ),
    ]
