# Generated by Django 5.1.5 on 2025-10-07 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_article_title_alter_article_up_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 10, 7, 19, 50, 5, 111636, tzinfo=datetime.timezone.utc)),
        ),
    ]
